# Site settings
title: Paul's Blog
header-img: img/home-bg.jpg
email: admin@pauldo.me
description: "Paul's Blog"
baseurl: ""
url: "http://192.168.1.163:4000"
twitter_username: pauldo
github_username:  pauldo
facebook_username:  pauldo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
